import 'package:get/get.dart';

/// 国际化
class HuuuaTranslate extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'zh_CN': {
      'rank': '排行榜',
      'rank_score': '分数',
      'Score': '分数',
      'rank_nickname': '昵称',
      'rank_nick_edit_success': '昵称修改成功',
      'rank_nick_edit_fail': '昵称修改失败',
      'rank_list_empty': '暂无排行榜数据',
      "@numleft stars left": "剩余@numleft个",
      "Bonus": "奖励",
      'Game Over!': '游戏失败!',
      'Congratulations! Next Level!': '恭喜进入下一关!',
      'Level': '关卡',
      'Target Score': '目标分数',
      'Target Reached!': '恭喜达成目标分数!',
      'get_refresh_times': '获取刷新次数',
      'close': '关闭',
      'claim_reward': '领取奖励',
      'watch_ad_reward': '观看广告奖励',
      'refresh_chances': '次刷新机会！',
      'free_claim': '免费领取',
      'try_tomorrow': '明日再来', // 添加中文明日可再领翻译
      'daily_free_claim': '每日免费领取', // 添加中文每日免费领取翻译
      'claim_refresh_success': '领取成功!',
      'Tips': '提示',
      'no_refresh_times': '您的刷新次数不足！',
      'loading': '加载中...',
      'cancel': '取消',
      'confirm': '确定',
      'ad_load_failed': '广告加载失败',
      'game_already_started_cannot_refresh': '游戏已开始，不能刷新!',
      'ad_cooldown': '广告冷却中',
      'today_ads_count': '今日次数',
      'minute': '分',
      'second': '秒',
      'Get Free Items': "获取免费道具",
      'Watch an ad to receive special items!': '观看广告以获取特殊道具！',
      'Watch to Claim': '观看领取',
      'Claim your free items every day and make your adventure easier!':
          '每天领取免费道具，使您的冒险更轻松！',
      'Tap a star to change its color!': '点击星星改变颜色!',
      'Double-tap the star to break it!': '双击目标星星，一锤敲掉！',
      'My Items': '我的道具',
      'retry': '重试',
      'Buy to Get Lots of Items': '购买获得大量道具',
      'START': '开始',
      'CONTINUE': '继续游戏',
      'OPEN': '打开',
      'claim': '领取',
      'Go Get': '前往获取',
      'Not enough uses': '使用次数不足',
      'Setting': '设置',
      'Login failed': '登录失败',
      'Network connection failed！\n Please check your network setings.':
          '网络连接失败！ \n 请检查网络是否打开。',
      'Retry': '重试网络连接',
      'Sound Effect': '音效',
      'Elimination Method': '消除方式',
      'BGM': '背景音乐',
      'New Game': '重新开始',
      'Revive': '立即复活',
      'My Lives': '我的生命',
      'Use': '使用',
      'No lives left': '生命不够',
      'GAME OVER': '游戏失败',
      'Cannot connect to Google Play leaderboards at this time.':
          '当前无法连接到 Google Play 排行榜。',
      "Congrats, you're back in the game!": "恭喜您，成功复活!",
    },
    'en_US': {
      'rank': 'Ranking',
      'rank_score': 'Score',
      'Score': 'Score',
      'rank_nickname': 'Nickname',
      'rank_nick_edit_success': 'Nickname updated successfully',
      'rank_nick_edit_fail': 'Failed to update nickname',
      'rank_list_empty': 'No ranking data available',
      "@numleft stars left": "@numleft stars left",
      "Bonus": "Bonus",
      'Game Over!': 'Game Over!',
      'Congratulations! Next Level!': 'Congratulations! Next Level!',
      'Level': 'Level',
      'Target Score': 'Target Score',
      'Target Reached!': 'Target Reached!',
      'get_refresh_times': 'Get Refresh Times',
      'close': 'Close',
      'claim_reward': 'Claim Reward',
      'watch_ad_reward': 'Watch Ad for',
      'refresh_chances': 'refresh chances!',
      'free_claim': 'Free Claim',
      'try_tomorrow': 'Try Tomorrow',
      'daily_free_claim': 'Daily Free Claim',
      'Tips': 'Tips',
      'no_refresh_times': 'You don\'t have enough refresh times!',
      'loading': 'Loading...',
      'cancel': 'Cancel',
      'confirm': 'Confirm',
      'claim_refresh_success': 'Refresh claimed successfully!',
      'ad_load_failed': 'Ad load failed',
      'game_already_started_cannot_refresh':
          'Game has already started, cannot refresh!',
      'ad_cooldown': 'Ad cooldown',
      'today_ads_count': 'Today Ads Count',
      'minute': 'm',
      'second': 's',
      'Get Free Items': "Get Free Items",
      'Watch an ad to receive special items!':
          'Watch an ad to receive special items!',
      'Watch to Claim': 'Watch to Claim',
      'Claim your free items every day and make your adventure easier!':
          'Claim your free items every day and make your adventure easier!',
      'Tap a star to change its color!': 'Tap a star to change its color!',
      'Double-tap the star to break it!': 'Double-tap the star to break it!',
      'My Items': 'My Items',
      'retry': 'Retry',
      'Buy to Get Lots of Items': 'Buy to Get Lots of Items',
      'START': 'START',
      'CONTINUE': 'CONTINUE',
      'OPEN': 'OPEN',
      'claim': 'CLAIM',
      'Go Get': 'Go Get',
      'Not enough uses': 'Not enough uses',
      'Setting': 'Setting',
      'Login failed': 'Login failed',
      'Network connection failed！\n Please check your network setings.':
          'Network connection failed！\n Please check your network setings.',
      'Retry': 'Retry',
      'Sound Effect': 'Sound Effect',
      'Elimination Method': 'Elimination Method',
      'BGM': 'BGM',
      'New Game': 'New Game',
      'Revive': 'Revive',
      'My Lives': 'My Lives',
      'No lives left': 'No lives left',
      'GAME OVER': 'GAME OVER',
      'Cannot connect to Google Play leaderboards at this time.':
          'Cannot connect to Google Play leaderboards at this time.',
      "Congrats, you're back in the game!":
          "Congrats, you're back in the game!",
    },
    'pt_BR11': {
      'rank': 'Ranking',
      'rank_score': 'Pontuação',
      'Score': 'Pontuação',
      'rank_nickname': 'Apelido',
      'rank_nick_edit_success': 'Apelido atualizado com sucesso',
      'rank_nick_edit_fail': 'Falha ao atualizar o apelido',
      'rank_list_empty': 'Nenhum dado de ranking disponível',
      "@numleft stars left": "Faltam @numleft estrelas",
      "Bonus": "Bônus",
      'Game Over!': 'Fim de jogo!',
      'Congratulations! Next Level!': 'Parabéns! Próximo nível!',
      'Level': 'Nível',
      'Target Score': 'Pontuação alvo',
      'Target Reached!': 'Pontuação alvo alcançada!',
      'get_refresh_times': 'Obter Tentativas de Atualização',
      'close': 'Fechar',
      'claim_reward': 'Resgatar Recompensa',
      'watch_ad_reward': 'Assista anúncio para',
      'refresh_chances': 'tentativas de atualização!',
      'free_claim': 'Resgate Gratuito',
      'try_tomorrow': 'Tente Amanhã',
      'daily_free_claim': 'Resgate Diário Gratuito',
      'Tips': 'Conselho',
      'no_refresh_times': 'Você não tem tentativas de atualização suficientes!',
      'loading': 'Carregando...',
      'cancel': 'Cancelar',
      'confirm': 'Confirmar',
      'claim_refresh_success': 'Atualização resgatada com sucesso!',
      'ad_load_failed': 'Falha ao carregar anúncio',
      'game_already_started_cannot_refresh':
          'Jogo já começou, não é possível atualizar!',
      'ad_cooldown': 'Tempo de espera do anúncio',
      'today_ads_count': 'Contagem de Anúncios do Dia',
      'minute': 'm',
      'second': 's',
      'Get Free Items': "Obtener Objetos Gratuitos",
      'Watch an ad to receive special items!':
          'Mira un anuncio para recibir objetos especiales!',
      'Watch to Claim': 'Mira para Recibir',
      'Claim your free items every day and make your adventure easier!':
          'Obtén objetos gratuitos cada día y haz tu aventura más fácil!',
      'Tap a star to change its color!':
          'Toca una estrella para cambiar su color!',
      'Double-tap the star to break it!':
          'Doble toque la estrella para romperla!',
      'My Items': 'Mis Objetos',
      'retry': 'Reintentar',
      'Buy to Get Lots of Items': 'Comprar para Obtener Muchos Objetos',
      'START': 'Comenzar',
      'CONTINUE': 'Continuar',
      'OPEN': 'Abrir',
      'claim': 'RECIBIR',
      'Go Get': 'Ir a Obtener',
      'Not enough uses': 'No hay suficientes usos',
      'Setting': 'Configuración',
      'Login failed': 'Login failed',
      'Network connection failed！\n Please check your network setings.':
          'Network connection failed！\n Please check your network setings.',
      'Retry': 'Retry',
      'Sound Effect': 'Sound Effect',
      'Elimination Method': 'Elimination Method',
      'BGM': 'BGM',
      'New Game': 'New Game',
      'Revive': 'Revive',
    },
    'es_MX11': {
      'rank': 'Clasificación',
      'rank_score': 'Puntuación',
      'Score': 'Puntuación',
      'rank_nickname': 'Apodo',
      'rank_nick_edit_success': 'Apodo actualizado con éxito',
      'rank_nick_edit_fail': 'Error al actualizar el apodo',
      'rank_list_empty': 'No hay datos de clasificación',
      "@numleft stars left": "Quedan @numleft estrellas",
      "Bonus": "Bono",
      'Game Over!': '¡Juego terminado!',
      'Congratulations! Next Level!': '¡Felicidades! Siguiente nivel!',
      'Level': 'Nivel',
      'Target Score': 'Puntuación objetivo',
      'Target Reached!': '¡Puntuación objetivo alcanzada!',
      'get_refresh_times': 'Obtener Veces de Actualización',
      'close': 'Cerrar',
      'claim_reward': 'Reclamar Recompensa',
      'watch_ad_reward': 'Mira anuncio para',
      'refresh_chances': 'veces de actualización!',
      'free_claim': 'Reclamo Gratis',
      'try_tomorrow': 'Inténtalo Mañana',
      'daily_free_claim': 'Reclamo Diario Gratis',
      'Tips': 'Conseil',
      'no_refresh_times': '¡No tienes suficientes veces de actualización!',
      'loading': 'Cargando...',
      'cancel': 'Cancelar',
      'confirm': 'Confirmar',
      'claim_refresh_success': '¡Actualización reclamada con éxito!',
      'ad_load_failed': 'Error al cargar anuncio',
      'game_already_started_cannot_refresh':
          'Juego ya ha comenzado, no se puede refrescar!',
      'ad_cooldown': 'Tiempo de espera de la publicidad',
      'today_ads_count': 'Contador de Publicidad del Día',
      'minute': 'm',
      'second': 's',
      'Get Free Items': "Obtenir Objets Gratuit",
      'Watch an ad to receive special items!':
          'Regardez une publicité pour obtenir des objets spéciaux !',
      'Watch to Claim': 'Regardez pour Obtenir',
      'Claim your free items every day and make your adventure easier!':
          'Obtenez des objets gratuits chaque jour et faites votre aventure plus facile !',
      'Tap a star to change its color!':
          'Touchez une étoile pour changer sa couleur!',
      'Double-tap the star to break it!':
          'Double-touchez l\'étoile pour la casser!',
      'My Items': 'Mes Objets',
      'retry': 'Réessayer',
      'Buy to Get Lots of Items': 'Comprar para Obtener Muchos Objetos',
      'START': 'Commencer',
      'CONTINUE': 'Continuer',
      'OPEN': 'Ouvrir',
      'claim': 'RECIBIR',
      'Go Get': 'Ir a Obtener',
      'Not enough uses': 'No hay suficientes usos',
      'Setting': 'Paramètres',
      'Login failed': 'Login failed',
      'Network connection failed！\n Please check your network setings.':
          'Network connection failed！\n Please check your network setings.',
      'Retry': 'Retry',
      'Sound Effect': 'Sound Effect',
      'Elimination Method': 'Elimination Method',
      'BGM': 'BGM',
      'New Game': 'New Game',
    },
    'fr_FR11': {
      'rank': 'Classement',
      'rank_score': 'Score',
      'Score': 'Score',
      'rank_nickname': 'Surnom',
      'rank_nick_edit_success': 'Surnom modifié avec succès',
      'rank_nick_edit_fail': 'Échec de la modification du surnom',
      'rank_list_empty': 'Aucune donnée de classement disponible',
      "@numleft stars left": "Il reste @numleft étoiles",
      "Bonus": "Bonus",
      'Game Over!': 'Fin de partie !',
      'Congratulations! Next Level!': 'Félicitations ! Niveau suivant !',
      'Level': 'Niveau',
      'Target Score': 'Score cible',
      'Target Reached!': 'Score cible atteint !',
      'get_refresh_times': 'Obtenir Nombre de Rafraîchissements',
      'close': 'Fermer',
      'claim_reward': 'Réclamer Récompense',
      'watch_ad_reward': 'Regardez la publicité pour',
      'refresh_chances': '机会 de rafraîchissement!',
      'free_claim': 'Réclamation Gratuite',
      'try_tomorrow': 'Essayez demain',
      'daily_free_claim': 'Réclamation Gratuite Quotidienne',
      'loading': 'Chargement...',
      'cancel': 'Annuler',
      'confirm': 'Confirmer',
      'claim_refresh_success': 'Rafraîchissement récupéré avec succès !',
      'ad_load_failed': "Échec du chargement de l'annonce",
      'Tips': 'Conseil',
      'no_refresh_times':
          'Vous n\'avez pas assez de tentatives de rafraîchissement !',
      'game_already_started_cannot_refresh':
          'Le jeu a déjà commencé, il n\'est pas possible de le rafraîchir !',
      'ad_cooldown': 'Temps d\'attente de la publicité',
      'today_ads_count': 'Compteur de Publicité du Jour',
      'minute': 'm',
      'second': 's',
      'Get Free Items': "Obtenir Objets Gratuit",
      'Watch an ad to receive special items!':
          'Regardez une publicité pour obtenir des objets spéciaux !',
      'Watch to Claim': 'Regardez pour Obtenir',
      'Claim your free items every day and make your adventure easier!':
          'Obtenez des objets gratuits chaque jour et faites votre aventure plus facile !',
      'Tap a star to change its color!':
          'Touchez une étoile pour changer sa couleur!',
      'Double-tap the star to break it!':
          'Double-touchez l\'étoile pour la casser!',
      'My Items': 'Mes Objets',
      'retry': 'Réessayer',
      'Buy to Get Lots of Items': 'Comprar para Obtener Muchos Objetos',
      'START': 'Commencer',
      'CONTINUE': 'Continuer',
      'OPEN': 'Ouvrir',
      'claim': 'RECIBIR',
      'Go Get': 'Ir a Obtener',
      'Not enough uses': 'No hay suficientes usos',
      'Setting': 'Paramètres',
      'Login failed': 'Login failed',
      'Network connection failed！\n Please check your network setings.':
          'Network connection failed！\n Please check your network setings.',
      'Retry': 'Retry',
      'Sound Effect': 'Sound Effect',
      'Elimination Method': 'Elimination Method',
      'BGM': 'BGM',
      'New Game': 'New Game',
    },
  };
}
